name: winawerlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.0
  - pip==20.1.1
  - numpy==1.18.5
  - matplotlib==3.2.1
  - pyyaml==5.3.1
  - nibabel==3.1.0
  - Pillow==7.1.2
  - pip:
      - neuropythy==0.11.5

