name: winawerlab
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.6
  - anaconda
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - matplotlib
  - scipy
  - seaborn
  - statsmodels
  - pandas
  - nipype>=1.1.1
  - pyyaml
  - pyosf
  - osfclient
  - h5py
  - nibabel
  - scikit-learn
  - scikit-image
  - pip:
      - neuropythy
      - pydeface
      - pybids>=0.7.0

